/* tslint:disable */
/* eslint-disable */
/**
 * Core Service
 * Open API Specification for Parker\'s \"Core\" Service
 *
 * The version of the OpenAPI document: 1.0
 * Contact: ypodeswa@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export * from './api'
export * from './configuration'
