version: '3.7'
services:
  kratos:
    image: oryd/kratos:v1.0
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - DSN=postgres://kratos:kratos_password@host.docker.internal:5440/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=warning
    command: serve -c /etc/config/kratos/kratos.yaml --dev --watch-courier
    volumes:
      - type: bind
        source: ./config/email-password
        target: /etc/config/kratos
    networks:
      - intranet
  # TODO: stop running this once I have my own frontend
  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v0.13.0
    ports:
      - '4455:4455'
    environment:
      - KRATOS_PUBLIC_URL=http://host.docker.internal:4433
      - KRATOS_BROWSER_URL=http://127.0.0.1:4433
      - PORT=4455
    networks:
      - intranet
    restart: on-failure
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - intranet
networks:
  intranet:
